// 두더지 게임 서비스워커.
// fetch 전략 = 네트워크 우선: 온라인이면 항상 네트워크에서 최신본을 받고, 캐시는 오프라인
// 폴백 전용으로만 갱신한다. (예전엔 stale-while-revalidate라 배포해도 "다음 실행"에야
// 반영돼 사용자 체감 대기가 길었음 — 온라인=항상 최신, 오프라인=마지막 캐시로 변경.)
// SHELL 목록 자체가 바뀔 때만 CACHE 를 올린다.
const CACHE = 'mole-game-v1010';

// 화면별 BGM(audio/bgm-*.mp3)은 v275 부터 SHELL 에 포함 — 기본 켜짐(v272)이라 항상 필요하고,
// 캐시가 안 돼 있으면 오프라인/느린망에서 재생 실패했음.
// vendor/face_mesh/*(약 10MB, 얼굴인식)는 SHELL 제외 — 사람두더지 메이커 처음 열 때만 필요.
// 처음 요청될 때 아래 fetch 핸들러가 알아서 캐시한다.
const SHELL = [
  './',
  './index.html',
  './style.css',
  '../cosmic-theme.css',
  '../common/settings.css',
  '../common/settings.js',
  '../common/i18n.js',
  './js/i18n-strings.js',
  './manifest.json',
  './icons/icon-192-hippo.png',
  './icons/icon-512-hippo.png',
  './assets/board-scene.jpg',
  './assets/board-scene-spring.jpg',
  './assets/board-scene-summer.jpg',
  './assets/board-scene-autumn.jpg',
  './assets/board-scene-winter.jpg',
  './assets/board-scene-night.jpg',
  './assets/avatar-mole.png',
  './assets/avatar-hippo.png',
  './assets/cloud1.png',
  './assets/cloud2.png',
  './assets/hammer.png',
  './assets/weapons/cannon-a1.png',
  './assets/weapons/cannon-a2.png',
  './assets/weapons/cannon-a3.png',
  './assets/weapons/cannon-a4.png',
  './assets/weapons/cannon-a5.png',
  './assets/weapons/cannon-ball.png',
  './assets/weapons/cannon-fx1.png',
  './assets/weapons/cannon-fx4.png',
  './assets/weapons/cannon-fx5.png',
  './assets/weapons/goldhammer.png',
  './assets/weapons/goldhammer-0.png',
  './assets/weapons/goldhammer-90.png',
  './assets/weapons/alipunch-jab.png',
  './assets/weapons/alipunch-straight.png',
  './assets/weapons/alipunch-upper.png',
  './assets/costume/char-blue_bears-detail.png',
  './assets/costume/char-red_wings-detail.png',
  './assets/costume/char-mount_stars-detail.png',
  './assets/costume/char-sun_giants-detail.png',
  './assets/costume/char-cloud_cups-detail.png',
  './assets/costume/emblem-blue_bears.png',
  './assets/costume/emblem-red_wings.png',
  './assets/costume/emblem-mount_stars.png',
  './assets/costume/emblem-sun_giants.png',
  './assets/costume/emblem-cloud_cups.png',
  './assets/costume/emblem-cap-blue_bears.png',
  './assets/costume/emblem-cap-red_wings.png',
  './assets/costume/emblem-cap-mount_stars.png',
  './assets/costume/emblem-cap-sun_giants.png',
  './assets/costume/emblem-cap-cloud_cups.png',
  './assets/costume2/card-blue_bears.jpg',
  './assets/costume2/card-red_wings.jpg',
  './assets/costume2/card-mount_stars.jpg',
  './assets/costume2/card-sun_giants.jpg',
  './assets/costume2/card-cloud_cups.jpg',
  './assets/costume2/bg-cabin.jpg',
  './assets/costume2/sign.png',
  './assets/costume2/tab-frame.png',
  './assets/costume2/tab-green.png',
  './assets/costume2/tab-blue.png',
  './assets/costume2/tab-green-press.png',
  './assets/costume2/tab-blue-press.png',
  './assets/settings2/card.png',
  './assets/settings2/head.png',
  './assets/settings2/ic-contact.png',
  './assets/settings2/ic-globe.png',
  './assets/settings2/ic-guide.png',
  './assets/settings2/ic-music.png',
  './assets/settings2/ic-noad.png',
  './assets/settings2/ic-shield.png',
  './assets/settings2/ic-sound.png',
  './assets/settings2/ic-trash.png',
  './assets/settings2/ic-vib.png',
  './assets/settings2/plank.png',
  './assets/settings2/slot-arrow.png',
  './assets/settings2/slot-drop.png',
  './assets/settings2/tog-off.png',
  './assets/settings2/tog-on.png',
  './assets/settings2/wood.png',
  './assets/mailbox/back.png',
  './assets/mailbox/bg.jpg',
  './assets/mailbox/btn-blue.png',
  './assets/mailbox/btn-green.png',
  './assets/mailbox/card.png',
  './assets/mailbox/env-blue.png',
  './assets/mailbox/env-heart.png',
  './assets/mailbox/env-pink.png',
  './assets/mailbox/env-read.png',
  './assets/mailbox/env-red.png',
  './assets/mailbox/env-yellow.png',
  './assets/mailbox/frame-bare.png',
  './assets/mailbox/ic-check.png',
  './assets/mailbox/ic-mail.png',
  './assets/mailbox/plank.png',
  './assets/mailbox/rw-coin.png',
  './assets/mailbox/rw-gift.png',
  './assets/mailbox/rw-heart.png',
  './assets/mailbox/rw-ticket.png',
  './assets/photo2/card-blue.png',
  './assets/photo2/card-gold.png',
  './assets/photo2/coll-bg.jpg',
  './assets/photo2/coll-card.png',
  './assets/photo2/emb-blue_bears.png',
  './assets/photo2/emb-cloud_cups.png',
  './assets/photo2/emb-mount_stars.png',
  './assets/photo2/emb-red_wings.png',
  './assets/photo2/emb-sun_giants.png',
  './assets/photo2/frame.png',
  './assets/photo2/stand.png',
  './assets/skin2/arrow-l.png',
  './assets/skin2/arrow-r.png',
  './assets/skin2/bg-skill.jpg',
  './assets/skin2/bg-weapon.jpg',
  './assets/skin2/ic-active.png',
  './assets/skin2/ic-passive.png',
  './assets/skin2/rt-cream.png',
  './assets/skin2/rt-panel.png',
  './assets/skin2/rt-plank.png',
  './assets/skin2/rt-slot.png',
  './assets/skin2/sk-cell.png',
  './assets/skin2/sk-next.png',
  './assets/skin2/sk-plank.png',
  './assets/skin2/sk-plus.png',
  './assets/skin2/sk-pnum.png',
  './assets/skin2/sk-prev.png',
  './assets/skin2/sk-restore.png',
  './assets/skin2/w-cardframe.png',
  './assets/costume2/box-frame-s.png',
  './assets/costume2/box-frame-w.png',
  './assets/costume2/leather-w.png',
  './assets/costume2/parchment.png',
  './assets/costume2/leaf-a.png',
  './assets/costume2/leaf-b.png',
  './assets/costume/logo.png',
  './assets/costume/bg-stadium.jpg',
  './assets/costume/clock.png',
  './assets/costume/trophy.png',
  './assets/skills/freeze.png',
  './assets/skills/gold-double-v2.png',
  './assets/skills/targeting.png',
  './assets/skills/carpet_bombing.png',
  './assets/skills/ai.png',
  './assets/skills/shield.png',
  './assets/skills/fever_time.png',
  './assets/skills/active_skill.png',
  './assets/skills/passive_skill.png',
  './assets/skills/restore.png',
  './assets/photo/background.jpg',
  './assets/photo/collection-grid.jpg',
  './assets/photo/pedestal_blue.png',
  './assets/photo/pedestal_gold.png',
  './assets/photo/collection-trophy.png',
  './assets/photo/collection-starbar.png',
  './assets/photo/characters/round_blue_bears.png',
  './assets/photo/characters/sturdy_blue_bears.png',
  './assets/photo/characters/sharp_blue_bears.png',
  './assets/photo/characters/round_red_wings.png',
  './assets/photo/characters/sturdy_red_wings.png',
  './assets/photo/characters/sharp_red_wings.png',
  './assets/photo/characters/round_mount_stars.png',
  './assets/photo/characters/sturdy_mount_stars.png',
  './assets/photo/characters/sharp_mount_stars.png',
  './assets/photo/characters/round_sun_giants.png',
  './assets/photo/characters/sturdy_sun_giants.png',
  './assets/photo/characters/sharp_sun_giants.png',
  './assets/photo/characters/round_cloud_cups.png',
  './assets/photo/characters/sturdy_cloud_cups.png',
  './assets/photo/characters/sharp_cloud_cups.png',
  './assets/costume/tshirt.png',
  './assets/shop/single-heart.png',
  './assets/shop/ad-icon.png',
  './assets/shop/mini-1.png',
  './assets/shop/mini-2.png',
  './assets/shop/mini-3.png',
  './assets/shop/mini-4.png',
  './assets/shop/mini-5.png',
  './assets/shop/mini-6.png',
  './assets/hippo/happy1.png',
  './assets/hippo/happy2.png',
  './assets/hippo/happy3.png',
  './assets/hippo/sad1.png',
  './assets/hippo/sad2.png',
  './assets/hippo/sad3.png',
  './assets/intro/1.jpg',
  './assets/intro/2.jpg',
  './assets/intro/3.jpg',
  './assets/moles/mole1.png',
  './assets/moles/mole2.png',
  './assets/moles/mole3.png',
  './assets/moles/mole4.png',
  './assets/moles/mole5.png',
  './assets/moles/mole6.png',
  './assets/moles/mole7.png',
  './assets/moles/mole8.png',
  './assets/moles/peek1.png',
  './assets/moles/peek2.png',
  './assets/moles/helmet.png',
  './assets/moles/hole.png',
  './assets/moles/hole-front.png',
  './assets/moles/hole-spring.png',
  './assets/moles/hole-front-spring.png',
  './assets/moles/hole-summer.png',
  './assets/moles/hole-front-summer.png',
  './assets/moles/hole-autumn.png',
  './assets/moles/hole-front-autumn.png',
  './assets/moles/hole-winter.png',
  './assets/moles/hole-front-winter.png',
  './assets/moles/hole-night.png',
  './assets/moles/hole-front-night.png',
  './assets/moles/shield.png',
  './assets/moles/rabbit.png',
  './assets/moles/rabbit-x.png',
  './assets/moles/tiger.png',
  './assets/moles/tiger-x.png',
  './assets/moles/hippo.png',
  './assets/moles/hippo-x.png',
  './assets/moles/lion.png',
  './assets/moles/lion-x.png',
  './assets/moles/dog.png',
  './assets/moles/dog-x.png',
  './assets/round-moles/mole1.png',
  './assets/round-moles/mole2.png',
  './assets/round-moles/mole3.png',
  './assets/round-moles/mole4.png',
  './assets/round-moles/mole5.png',
  './assets/round-moles/mole6.png',
  './audio/hammer-sfx-01.mp3',
  './audio/hammer-sfx-02.mp3',
  './audio/mole-emerge.mp3',
  './audio/punch-jab.mp3',
  './audio/punch-straight.mp3',
  './audio/punch-upper.mp3',
  './audio/punch-hookL.mp3',
  './audio/punch-hookR.mp3',
  './audio/hit1.mp3',
  './audio/hit2.mp3',
  './audio/hit3.mp3',
  './audio/hit4.mp3',
  './audio/bgm-home-1.mp3',
  './audio/bgm-home-2.mp3',
  './audio/bgm-home-3.mp3',
  './audio/bgm-home-4.mp3',
  './audio/bgm-home-5.mp3',
  './audio/bgm-home-6.mp3',
  './assets/home-showcase/arcade-1.jpg',
  './assets/home2/splash-art.webp',
  './assets/home-showcase/arcade-2.jpg',
  './assets/home-showcase/arcade-3.jpg',
  './assets/home-showcase/arcade-4.jpg',
  './assets/home-showcase/arcade-5.jpg',
  './assets/home-showcase/arcade-6.jpg',
  './assets/home-showcase/arcade-7.jpg',
  './assets/home-showcase/arcade-8.jpg',
  './assets/home-showcase/arcade-9.jpg',
  './assets/home-showcase/spring-1.jpg',
  './assets/home-showcase/spring-2.jpg',
  './assets/home-showcase/spring-3.jpg',
  './assets/home-showcase/spring-4.jpg',
  './assets/home-showcase/spring-5.jpg',
  './assets/home-showcase/spring-6.jpg',
  './assets/home-showcase/spring-7.jpg',
  './assets/home-showcase/spring-8.jpg',
  './assets/home-showcase/spring-9.jpg',
  './assets/home-showcase/summer-1.jpg',
  './assets/home-showcase/summer-2.jpg',
  './assets/home-showcase/summer-3.jpg',
  './assets/home-showcase/summer-4.jpg',
  './assets/home-showcase/summer-5.jpg',
  './assets/home-showcase/summer-6.jpg',
  './assets/home-showcase/summer-7.jpg',
  './assets/home-showcase/summer-8.jpg',
  './assets/home-showcase/summer-9.jpg',
  './assets/home-showcase/autumn-1.jpg',
  './assets/home-showcase/autumn-2.jpg',
  './assets/home-showcase/autumn-3.jpg',
  './assets/home-showcase/autumn-4.jpg',
  './assets/home-showcase/autumn-5.jpg',
  './assets/home-showcase/autumn-6.jpg',
  './assets/home-showcase/autumn-7.jpg',
  './assets/home-showcase/autumn-8.jpg',
  './assets/home-showcase/autumn-9.jpg',
  './assets/home-showcase/winter-1.jpg',
  './assets/home-showcase/winter-2.jpg',
  './assets/home-showcase/winter-3.jpg',
  './assets/home-showcase/winter-4.jpg',
  './assets/home-showcase/winter-5.jpg',
  './assets/home-showcase/winter-6.jpg',
  './assets/home-showcase/winter-7.jpg',
  './assets/home-showcase/winter-8.jpg',
  './assets/home-showcase/winter-9.jpg',
  './audio/bgm-more.mp3',
  './audio/bgm-game-1.mp3',
  './js/levels.js',
  './js/progress.js',
  './js/rng.js',
  './js/combo-score.js',
  './js/grid-partition.js',
  './js/spawn-scheduler.js',
  './js/mole-sprites.js',
  './js/costume-teams.js',
  './js/skills.js',
  './js/photo-studio.js',
  './js/face-detect.js',
  './js/pop-elements.js',
  './js/hole-layer.js',
  './js/hit-fx.js',
  './js/lane-hammer.js',
  './js/lane-cannon.js',
  './js/lane-boxing.js',
  './js/weapon-pool.js',
  './js/lane-controls.js',
  './js/region-reveal.js',
  './js/hud.js',
  './js/sky.js',
  './js/screen-nav.js',
  './js/intro.js',
  './js/economy.js',
  './js/ads.js',
  './js/face-maker.js',
  './js/shop.js',
  './js/daily.js',
  './js/workshop.js',
  './js/round-map.js',
  './js/quest.js',
  './js/rhythm.js',
  './js/face-studio.js',
  './js/score-screen.js',
  './js/settings-screen.js',
  './js/inventory-screen.js',
  './js/mailbox.js',
  './js/game.js'
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;

  // 네트워크 우선: 온라인이면 항상 최신본을 바로 받는다(캐시는 오프라인 폴백용으로만 갱신).
  // 예전엔 stale-while-revalidate(캐시본 먼저)라 "항상 한 번 밀려서 반영"됐음 — 사용자가
  // 폰에서 대기가 길다고 느껴 네트워크 우선으로 변경.
  e.respondWith((async () => {
    try {
      // js/css 는 no-cache(브라우저 HTTP 캐시 건너뛰고 서버 재검증) — 배포 직후 index.html 만
      // 새로 오고 js 하나가 캐시본이라 i18n 키가 날것으로 뜨는 "반쪽 갱신" 방지. navigate 등은 평소대로.
      // navigate(첫 화면 index.html)도 no-cache(v739) — GitHub Pages 가 index.html 을 max-age=600 으로 줘서, 설치 앱
      // (start_url=index.html, 브라우저 탭 /mole/ 과 캐시 키가 다름)이 최대 10분간 옛 첫 화면을 쓰며 새 배포를 못 알아챘음.
      const revalidate = e.request.mode === 'navigate' || e.request.destination === 'script' || e.request.destination === 'style';
      // 첫 화면(navigate)은 주소에 매번 다른 꼬리표를 붙여 GitHub Pages CDN 의 서버별 옛 복사본(최대 10분)을 건너뛰고
      // 원본에서 받는다(v740) — 연속 배포 직후 앱 버전이 새 것↔예전 것으로 왔다 갔다 하던 문제.
      let req = e.request;
      if (e.request.mode === 'navigate') {
        const u = new URL(e.request.url); u.searchParams.set('_fresh', Date.now());
        req = new Request(u.toString(), { credentials: 'same-origin' });
      }
      const res = await fetch(req, revalidate ? { cache: 'no-store' } : undefined);
      if (res && res.ok && (res.type === 'basic' || res.type === 'cors')) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy));
      }
      return res;
    } catch (err) {
      const cached = await caches.match(e.request);
      if (cached) return cached;
      // 오프라인 + 캐시에 없음. undefined 를 반환하면 브라우저가 "인터넷 연결 없음" 페이지를 띄우므로 금지.
      if (e.request.mode === 'navigate') {
        return (await caches.match('./index.html')) || (await caches.match('./')) || Response.error();
      }
      return Response.error();
    }
  })());
});
